services:
  - type: web
    name: asl-recognition-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
