version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - model_data:/app/models
      - training_data:/app/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: python app.py
    networks:
      - asl-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - asl-network

volumes:
  model_data:
  training_data:

networks:
  asl-network:
    driver: bridge